Cliente.UI/Controllers/CidadesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cliente.UI.Data;
using Cliente.UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace Cliente.UI.Controllers
{
    [Authorize]
    public class CidadesController : Controller
    {
        private readonly Services.IRepositoryGeneric<Cidade> repositoryCidade;
        private readonly Services.IRepositoryGeneric<Estado> repositoryEstado;
        

        public CidadesController(Services.IRepositoryGeneric<Cidade> repoCidade,
                                 Services.IRepositoryGeneric<Estado> repoEstado)
        {
            repositoryCidade = repoCidade;
            repositoryEstado = repoEstado;
        }

        // GET: Cidades
        public async Task<IActionResult> Index(int? id)
        {
            var applicationDbContext = await repositoryCidade.GetAllAsync(c => id == null || c.EstadoId == id, c => c.Estado);
            return View(applicationDbContext);
        }

        // GET: Cidades/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cidade = await repositoryCidade.GetAsync(id.Value);
            ViewData["EstadoId"] = new SelectList(repositoryEstado.GetAll(), "EstadoId", "Nome");
            if (cidade == null)
            {
                return NotFound();
            }

            return View(cidade);
        }

        // GET: Cidades/Create
        public IActionResult Create()
        {
            ViewData["EstadoId"] = new SelectList(repositoryEstado.GetAll(), "Id", "Nome");
            return View();
        }

        // POST: Cidades/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,EstadoId")] Cidade cidade)
        {
            if (ModelState.IsValid)
            {
                await repositoryCidade.InsertAsync(cidade);
                return RedirectToAction(nameof(Index));
            }
            ViewData["EstadoId"] = new SelectList(await repositoryCidade.GetAllAsync(), "EstadoId", "Nome", cidade.EstadoId);
            return View(cidade);
        }

        // GET: Cidades/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cidade = await repositoryCidade.GetAsync(id.Value);

            if (cidade == null)
            {
                return NotFound();
            }

            var list = await repositoryEstado.GetAllAsync();

            ViewData["EstadoId"] = new SelectList(list, "Id", "Nome", cidade.EstadoId);
            return View(cidade);
        }

        // POST: Cidades/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,EstadoId")] Cidade cidade)
        {
            if (id != cidade.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await repositoryCidade.UpdateAsync(cidade.Id, cidade);
                return RedirectToAction(nameof(Index));
            }
            ViewData["EstadoId"] = new SelectList(repositoryEstado.GetAll(), "Id", "Nome", cidade.EstadoId);
            return View(cidade);
        }

        // GET: Cidades/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cidade = await repositoryCidade.GetAsync(id);

            if (cidade == null)
            {
                return NotFound();
            }

            return View(cidade);
        }

        // POST: Cidades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await repositoryCidade.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Cliente.UI/Controllers/EstadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cliente.UI.Models;
using Microsoft.AspNetCore.Authorization;

namespace Cliente.UI.Controllers
{
    [Authorize]
    public class EstadosController : Controller
    {
        private readonly Services.IRepositoryGeneric<Estado> repositoryEstado;

        public EstadosController(Services.IRepositoryGeneric<Estado> repoEstado)
        {
            repositoryEstado = repoEstado;
        }

        // GET: Estados
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = await repositoryEstado.GetAllAsync();
            return View(applicationDbContext);
        }

        // GET: Estados/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estado = await repositoryEstado.GetAsync(id.Value);
            if (estado == null)
            {
                return NotFound();
            }

            return View(estado);
        }

        // GET: Estados/Create
        public IActionResult Create()
        {
            ViewData["EstadoId"] = new SelectList(repositoryEstado.GetAll(), "EstadoId", "Nome");
            return View();
        }

        // POST: Estados/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome")] Estado estado)
        {
            if (ModelState.IsValid)
            {

                await repositoryEstado.InsertAsync(estado);
                return RedirectToAction(nameof(Index));
            }
            ViewData["EstadoId"] = new SelectList(repositoryEstado.GetAll(), "EstadoId", "Nome");
            return View(estado);
        }

        // GET: Estados/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estado = await repositoryEstado.GetAsync(id.Value);

            if (estado == null)
            {
                return NotFound();
            }
            ViewData["EstadoId"] = new SelectList(repositoryEstado.GetAll(), "EstadoId", "Nome");
            return View(estado);
        }

        // POST: Estados/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome")] Estado estado)
        {
            if (id != estado.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await repositoryEstado.UpdateAsync(id, estado);
                return RedirectToAction(nameof(Index));
            }
            ViewData["EstadoId"] = new SelectList(repositoryEstado.GetAll(), "EstadoId", "Nome");
            return View(estado);
        }

        // GET: Estados/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estado = await repositoryEstado.GetAsync(id);
            if (estado == null)
            {
                return NotFound();
            }

            return View(estado);
        }

        // POST: Estados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await repositoryEstado.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Cliente.UI/Controllers/MarcasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cliente.UI.Data;
using Cliente.UI.Models;
using Microsoft.AspNetCore.Authorization;

namespace Cliente.UI.Controllers
{
    [Authorize]
    public class MarcasController : Controller
    {
        private readonly Services.IRepositoryGeneric<Marca> repositoryMarca;

        public MarcasController(Services.IRepositoryGeneric<Marca> repoMarca)
        {
            repositoryMarca = repoMarca;
        }

        // GET: Marcas
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = await repositoryMarca.GetAllAsync();
            return View(applicationDbContext);
        }

        // GET: Marcas/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marca = await repositoryMarca.GetAsync(id.Value);
            if (marca == null)
            {
                return NotFound();
            }

            return View(marca);
        }

        // GET: Marcas/Create
        public IActionResult Create()
        {
            ViewData["MarcaId"] = new SelectList(repositoryMarca.GetAll(), "Id", "Nome");
            return View();          
        }

        // POST: Marcas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome")] Marca marca)
        {
            if (ModelState.IsValid)
            {
                await repositoryMarca.InsertAsync(marca);
                return RedirectToAction(nameof(Index));
            }
            ViewData["MarcaId"] = new SelectList(repositoryMarca.GetAll(), "Id", "Nome");
            return View(marca);
        }

        // GET: Marcas/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marca = await repositoryMarca.GetAsync(id.Value);
            if (marca == null)
            {
                return NotFound();
            }
            ViewData["MarcaId"] = new SelectList(repositoryMarca.GetAll(), "Id", "Nome");
            return View(marca);
        }

        // POST: Marcas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Nome")] Marca marca)
        {
            if (id != marca.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await repositoryMarca.UpdateAsync(id, marca);
                return RedirectToAction(nameof(Index));
            }
            ViewData["MarcaId"] = new SelectList(repositoryMarca.GetAll(), "Id", "Nome");
            return View(marca);
        }

        // GET: Marcas/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marca = await repositoryMarca.GetAsync(id);
            if (marca == null)
            {
                return NotFound();
            }

            return View(marca);
        }

        // POST: Marcas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            await repositoryMarca.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

Cliente.UI/Controllers/PessoasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cliente.UI.Data;
using Cliente.UI.Models;
using Microsoft.AspNetCore.Authorization;

namespace Cliente.UI.Controllers
{
    [Authorize]
    public class PessoasController : Controller
    {
        private readonly Services.IRepositoryGeneric<Pessoa> repositoryPessoa;
        private readonly Services.IRepositoryGeneric<Endereco> repositoryEndereco;

        public PessoasController(Services.IRepositoryGeneric<Pessoa> repoPessoa,
                                Services.IRepositoryGeneric<Endereco> repoEndereco)
        {
            repositoryPessoa = repoPessoa;
            repositoryEndereco = repoEndereco;
        }

        // GET: Pessoas
        public async Task<IActionResult> Index(int? id)
        {
            var applicationDbContext = await repositoryPessoa.GetAllAsync(c => id == null || c.EnderecoId == id, c => c.Endereco);
            return View(applicationDbContext);
        }

        // GET: Pessoas/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoa = await repositoryPessoa.GetAsync(id.Value);
            ViewData["EnderecoId"] = new SelectList(repositoryEndereco.GetAll(), "Id", "Nome");
            if (pessoa == null)
            {
                return NotFound();
            }

            return View(pessoa);
        }

        // GET: Pessoas/Create
        public IActionResult Create()
        {
            ViewData["EnderecoId"] = new SelectList(repositoryEndereco.GetAll(), "Id", "Cep");
            return View();
        }

        // POST: Pessoas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Cpf,EnderecoId,Numero,Complemento,Password")] Pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                await repositoryPessoa.InsertAsync(pessoa);
                return RedirectToAction(nameof(Index));
            }
            ViewData["EnderecoId"] = new SelectList(await repositoryEndereco.GetAllAsync(), "Id", "Cep", pessoa.Id);
            return View(pessoa);
        }

        // GET: Pessoas/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoa = await repositoryPessoa.GetAsync(id.Value);
            if (pessoa == null)
            {
                return NotFound();
            }
            ViewData["EnderecoId"] = new SelectList(repositoryEndereco.GetAll(), "Id", "Cep", pessoa.EnderecoId);
            return View(pessoa);
        }

        // POST: Pessoas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Nome,Cpf,EnderecoId,Numero,Complemento,Password")] Pessoa pessoa)
        {
            if (id != pessoa.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await repositoryPessoa.UpdateAsync(pessoa.Id, pessoa);
                return RedirectToAction(nameof(Index));
            }
            ViewData["EnderecoId"] = new SelectList(repositoryEndereco.GetAll(), "Id", "Cep");
            return View(pessoa);
        }

        // GET: Pessoas/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoa = await repositoryPessoa.GetAsync(id);
            if (pessoa == null)
            {
                return NotFound();
            }

            return View(pessoa);
        }

        // POST: Pessoas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            await repositoryPessoa.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Cliente.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cliente.UI</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Cliente.UI</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>                       

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Enderecos" asp-action="Index">Cadastrar Endereços</a></li>
                                <li><a asp-area="" asp-controller="Estados" asp-action="Index">Cadastrar Estados</a></li>
                                <li><a asp-area="" asp-controller="Cidades" asp-action="Index">Cadastrar Cidades</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a asp-area="" asp-controller="Pessoas" asp-action="Index">Cadastrar Clientes</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a asp-area="" asp-controller="TipoPagamentos" asp-action="Index">Cadastrar Tipo de Pagamento </a></li>
                                <li><a asp-area="" asp-controller="FormaPagamentoes" asp-action="Index">Cadastrar Forma de Pagamento</a></li>
                                <li><a asp-area="" asp-controller="NotasFiscais" asp-action="Index">Cadastrar Nota Fiscal</a></li>
                                <li><a asp-area="" asp-controller="ItemNotas" asp-action="Index">Nota</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a asp-area="" asp-controller="Produtos" asp-action="Index">Cadastrar Produto</a></li>
                                <li><a asp-area="" asp-controller="Marcas" asp-action="Index">Cadastrar Marca</a></li>                            
                            </ul>
                        </li>
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
    </header>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Cliente.UI</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>